"""Client-side PQC test helpers.

These helpers model the production device architecture: quantum-safe keypairs
are generated locally by the client and only the *public* keys are registered
against the user record. The server never generates, receives, stores,
decrypts, or signs with a PQC private key.
"""

import base64
import uuid
from datetime import datetime, timezone

from pqcrypto.kem import ml_kem_768
from pqcrypto.sign import ml_dsa_65

from core.config import settings
from core.security import decode_token
from models.user import User
from services.crypto_service import CryptoService

ALGORITHM_VERSION = "ML-KEM-768+ML-DSA-65"

# Device signing secrets generated by this helper process, keyed by user id.
# These stand in for the private keys that live in a real device keystore.
_DEVICE_SIGNING_SECRETS: dict = {}


def register_device_public_keys(user) -> bytes:
    """Attach a freshly generated device identity's public keys to ``user``.

    Mirrors real device onboarding: the keypair is created "on the device" and
    only the ML-KEM-768/ML-DSA-65 public keys are persisted.

    Returns:
        bytes: the ML-DSA-65 secret key, so tests can produce client-style
        signatures locally exactly as a device would.
    """
    kem_public, _kem_secret = ml_kem_768.generate_keypair()
    signature_public, signature_secret = ml_dsa_65.generate_keypair()
    user.pq_kem_public_key = base64.b64encode(kem_public).decode("ascii")
    user.pq_signature_public_key = base64.b64encode(signature_public).decode("ascii")
    user.pq_algorithm_version = ALGORITHM_VERSION
    user.pq_key_created_at = datetime.now(timezone.utc)
    return signature_secret


def sign_payload(signature_secret: bytes, payload: bytes) -> str:
    """Produce a Base64 ML-DSA-65 signature exactly as a client device would."""
    return base64.b64encode(ml_dsa_65.sign(signature_secret, payload)).decode("ascii")


def device_signing_secret(session, user) -> bytes:
    """Return ``user``'s device signing secret, registering its public key.

    Mirrors device onboarding: the keypair is generated locally and only the
    public key is persisted on the user record.
    """
    secret = _DEVICE_SIGNING_SECRETS.get(user.id)
    if secret is None:
        secret = register_device_public_keys(user)
        _DEVICE_SIGNING_SECRETS[user.id] = secret
        session.add(user)
        session.commit()
        session.refresh(user)
    return secret


def client_signature_fields(
    session, user, conversation_id, content_encrypted, message_type="text", created_at=None
) -> dict:
    """Signature fields a real client device attaches to an outgoing message."""
    created_at = created_at or datetime.now(timezone.utc)
    payload = CryptoService._message_payload(
        conversation_id, user.id, message_type, content_encrypted, created_at, None
    )
    return {
        "signature": sign_payload(device_signing_secret(session, user), payload),
        "signature_created_at": created_at,
    }


def _user_from_authorization(session, headers):
    """Resolve the authenticated user from an Authorization header."""
    if not headers:
        return None
    token = headers.get("Authorization", "")
    if not token.startswith("Bearer "):
        return None
    try:
        payload = decode_token(token[len("Bearer "):])
        subject = payload.get("sub")
        if not subject:
            return None
        return session.query(User).filter(User.id == uuid.UUID(str(subject))).first()
    except Exception:
        return None


def install_signing_service_calls(session, monkeypatch, namespace):
    """Make a test module's ``send_message``/``edit_message`` sign like a client.

    Tests that are not about signing are converted to the real client-side
    architecture: the outgoing payload carries a genuine device-produced
    ML-DSA-65 signature instead of relying on the server to sign. The
    production enforcement path is untouched - a call with no signature still
    fails, which the dedicated Phase 0 regression tests assert directly.
    """
    original_send = namespace.get("send_message")
    if original_send is not None:
        def send_with_client_signature(*args, **kwargs):
            if settings.PQC_ENABLED and not kwargs.get("signature"):
                user = (
                    session.query(User).filter(User.id == kwargs.get("sender_id")).first()
                )
                if user is not None and kwargs.get("content_encrypted"):
                    kwargs = {
                        **kwargs,
                        **client_signature_fields(
                            session,
                            user,
                            kwargs.get("conversation_id"),
                            kwargs["content_encrypted"],
                            kwargs.get("message_type", "text"),
                            kwargs.get("signature_created_at"),
                        ),
                    }
            return original_send(*args, **kwargs)

        monkeypatch.setitem(namespace, "send_message", send_with_client_signature)

    original_edit = namespace.get("edit_message")
    if original_edit is not None:
        def edit_with_client_signature(*args, **kwargs):
            if settings.PQC_ENABLED and not kwargs.get("signature"):
                from models.message import Message

                user = (
                    session.query(User).filter(User.id == kwargs.get("user_id")).first()
                )
                message = (
                    session.query(Message)
                    .filter(Message.id == kwargs.get("message_id"))
                    .first()
                )
                if user is not None and message is not None and kwargs.get("content_encrypted"):
                    kwargs = {
                        **kwargs,
                        **client_signature_fields(
                            session,
                            user,
                            message.conversation_id,
                            kwargs["content_encrypted"],
                            message.message_type,
                            kwargs.get("signature_created_at"),
                        ),
                    }
            return original_edit(*args, **kwargs)

        monkeypatch.setitem(namespace, "edit_message", edit_with_client_signature)


def install_signing_api_calls(client, session, monkeypatch):
    """Make TestClient message-creation requests carry a client signature.

    Only requests that look like message creation are touched, so auth and
    other endpoints are unaffected.
    """
    original_post = client.post

    def post_with_client_signature(url, *args, **kwargs):
        body = kwargs.get("json")
        if (
            isinstance(body, dict)
            and body.get("conversation_id")
            and body.get("content_encrypted")
        ):
            user = _user_from_authorization(session, kwargs.get("headers"))
            if user is not None:
                conversation_id = body["conversation_id"]
                if isinstance(conversation_id, str):
                    conversation_id = uuid.UUID(conversation_id)
                kwargs["json"] = {
                    **body,
                    **client_signature_fields(
                        session,
                        user,
                        conversation_id,
                        body["content_encrypted"],
                        body.get("message_type", "text"),
                    ),
                }
                # Real clients emit an ISO-8601 string (see ChatPage.jsx);
                # keep the JSON body serializable exactly as production.
                kwargs["json"]["signature_created_at"] = kwargs["json"][
                    "signature_created_at"
                ].isoformat()
        return original_post(url, *args, **kwargs)

    monkeypatch.setattr(client, "post", post_with_client_signature)